cakephp/queue

- LICENSE.txt
This helps Github recognize it as MIT license.
> Match the license text to the one used in core.

- src/Consumption/QueueExtension.php
- src/Shell/WorkerShell.php
The namespace should follow upstream, which uses Consumption.
Also remove the TODO as this is not possible since there can only be a single consumption extension added to the internal queue consumer.
> fix: use correct namespace for QueueExtension

- src/QueueManager.php
- tests/TestCase/QueueManagerTest.php
I'm not sure how to proceed on QueueManager::push() as I've not figured out where in Enqueue to attach a listener/extension/callback/logger. @josegonzalez do you know how that could be done?
> Add more tests.

- src/Mailer/QueueTrait.php
- tests/TestCase/Mailer/QueueTraitTest.php
The QueueTrait referenced 2 classes:
```php
use Queue\Job\MailerJob;
use Queue\QueueManager;
```
I think it's meant to be:
```php
use Cake\Queue\Job\MailerJob;
use Cake\Queue\QueueManager;
```
I updated the import statements. Also I provided a unit test of the QueueTrait.
> Queue trait tests

- src/Job/JobInterface.php
- src/Mailer/QueueTrait.php
- src/QueueManager.php
- tests/TestCase/Mailer/QueueTraitTest.php
- tests/TestCase/QueueManagerTest.php
- tests/app/TestApp/WelcomeMailer.php
The tests provided in #30 exposed a few more problems that needed to be
fixed.
* The getName() method doesn't exist on Mailer.
* The `callable` type requires the value to be statically callable,
which MailerJob::execute() is not.
* I'm not a fan of mocks and would rather test with an implementation.
> Fix failing QueueTrait tests.

- src/Command/WorkerCommand.php
- tests/TestCase/Command/WorkerCommandTest.php
- tests/TestCase/Mailer/QueueTraitTest.php
- tests/app/TestApp/WelcomeMailerListener.php
This PR moves the Shell to a Command class. It also cleans up a few issues. 
I had  some test that pass individually but not in the suite. This is because of the statics found on line 91-98 of QueueManager. I can't change the configuration for different testing scenarios. So many statics in this library. Do these restrictions in the QueueManager need to remain? Can here be a static reset in the QueueManager so these things can be tested? For now I'm just running them in separate processes.
Also, there is an option called "config" that is meant to be an array? It passes the listener. My guess is that should come from the config like the "url". Is that right?
> WorkerShell to WorkerCommand

- src/Command/WorkerCommand.php
- tests/TestCase/Command/WorkerCommandTest.php
This is a pull request for the following issue.
https://github.com/cakephp/queue/issues/50
Updated the Cli option to allow specifying the processor name.
（This is my first pull request, so I apologize if this is incorrect.）
> Add support for setting the processor name in the Cli option.

- docs/en/index.rst
Added documentation that the processor name can be set in the worker's Cli option. https://github.com/cakephp/queue/pull/51
> docs: Added documentation that the processor name can be set in the worker's Cli option.

- src/QueueManager.php
edited QueueManager
if the config url key is a string, will be converted to array and all the client config will be setted.
if the config url key is an array, the client config will be merged
> added support for simply using different queue than default

- phpunit.xml.dist
- src/Plugin.php
- tests/TestCase/Command/WorkerCommandTest.php
Only set configuration data once. This is relevant when integration tests are used and bootstrap() is called multiple times.
Fixes #67
> Don't set Queue configuration multiple times

- docs/en/index.rst
The inner most values were indented with six spaces instead of four. The cookbook also doesn't show the extra level of indentation at the beginning so I removed it.
> Fix Documentation Code Example Indentation

- src/Job/Message.php
This fixes the notice I get when running the queue worker on PHP 8.1.
> Notice: Deprecated (8192): Return type of Cake\Queue\Job\Message::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> Fix jsonSerialize Deprecation Notice

- tests/TestCase/Command/WorkerCommandTest.php
Cleanup `Configure::write()` calls in tests. Makes the code look more clean.
> Cleanup Configure::write() Calls

- tests/TestCase/Job/MailerJobTest.php
- tests/TestCase/Queue/ProcessorTest.php
- Remove deprecated `setMethods` PHPUnit Mock calls in favor of `onlyMethods`
- Fix doc blocks classes
> Minor Test Cleanup

- docs/en/index.rst
- src/Job/Message.php
- src/QueueManager.php
- tests/TestCase/Job/MailerJobTest.php
- tests/TestCase/Job/MessageTest.php
- tests/TestCase/Queue/ProcessorTest.php
We store arguments on the queue as an array, but there is only ever one element in that array. I can't think of a reason to have an array with only one element in it.
Old Structure:
```json
{"queue":"default","class":["App\\Job\\HelloJob","execute"],"args":[{"name":"World","number":1,"bool":true}]}
```
New Structure:
```json
{"queue":"default","class":["App\\Job\\HelloJob","execute"],"data":{"name":"World","number":1,"bool":true}}
```
> Flatten Arguments in Queue Payload

- src/Command/JobCommand.php
- src/Plugin.php
Since shells are deprecated this should probably be a command.
I wasn't sure if I should namespace the bake command to something like `bake queue job` in case we add more things to bake in the future. The pattern I could see from other plugins seems to be a single name.
> Convert Bake Job Shell to Command

- docs/en/index.rst
- src/Job/Message.php
- src/Mailer/QueueTrait.php
- src/QueueManager.php
- tests/TestCase/Command/WorkerCommandTest.php
- tests/TestCase/Queue/ProcessorTest.php
- tests/TestCase/QueueManagerTest.php
- tests/test_app/src/Job/LogToDebugJob.php
This will make the code in projects that use the queue much cleaner. Instead of having to pass `[Job::class, 'execute']` everywhere the user will be able to pass `Job::class` directly  and the `'execute'` portion will be added automatically.
Closes #78
> Change QueueManager::push to Only Accept Job Classes

- src/Plugin.php
- tests/TestCase/PluginTest.php
> Implement exception if missing Queue config key. Fixes #102

- composer.json
- config/Migrations/20221007202459_CreateFailedJobs.php
- docs/en/index.rst
- phpunit.xml.dist
- src/Command/PurgeFailedCommand.php
- src/Command/RequeueCommand.php
- src/Command/WorkerCommand.php
- src/Consumption/LimitAttemptsExtension.php
- src/Job/Message.php
- src/Listener/FailedJobsListener.php
- src/Model/Entity/FailedJob.php
- src/Model/Table/FailedJobsTable.php
- src/Plugin.php
- src/Queue/Processor.php
- src/QueueManager.php
- tests/Fixture/FailedJobsFixture.php
- tests/TestCase/Command/PurgeFailedCommandTest.php
- tests/TestCase/Command/RequeueCommandTest.php
- tests/TestCase/Consumption/LimitAttemptsExtensionTest.php
- tests/TestCase/DebugLogTrait.php
- tests/TestCase/Listener/FailedJobsListenerTest.php
- tests/TestCase/Queue/ProcessorTest.php
- tests/bootstrap.php
- tests/test_app/src/Job/MaxAttemptsIsThreeJob.php
This adds support for storing and manually requeuing failed jobs (defined as jobs that have exceeded `maxAttempts`). This would lay some groundwork for https://github.com/cakephp/queue/issues/11.
This is a somewhat significant set of changes so I'm very open to any feedback.
Many thanks to @amayer5125 for his suggestions and review.
> Add failed jobs support

- docs/en/index.rst
- src/Command/JobCommand.php
- src/Command/WorkerCommand.php
- src/Consumption/RemoveUniqueJobIdFromCacheExtension.php
- src/Job/Message.php
- src/Listener/FailedJobsListener.php
- src/QueueManager.php
- templates/bake/job.twig
- tests/TestCase/Consumption/LimitAttemptsExtensionTest.php
- tests/TestCase/Consumption/RemoveUniqueJobIdFromCacheExtensionTest.php
- tests/TestCase/QueueManagerTest.php
- tests/TestCase/Task/JobTaskTest.php
- tests/comparisons/JobTaskWithUnique.php
- tests/test_app/src/Job/UniqueJob.php
This adds support for queueing unique jobs. When enabled for a given job, it will be (nearly) guaranteed that no other jobs with the same data will be present on the queue simultaneously.
Sometimes when the same job with the same payload is queued multiple times before other instances of the job are able to be run, it's not useful to run the job multiple times, once is enough, so this aims to address that.
> Add support for unique jobs

- src/Job/SendMailJob.php
- src/Mailer/Transport/QueueTransport.php
- tests/TestCase/Job/SendMailJobTest.php
- tests/TestCase/Listener/FailedJobsListenerTest.php
- tests/TestCase/Mailer/Transport/QueueTransportTest.php
- tests/test_app/files/test.txt
Fixes #64 
I have implemented `QueueTransport` to automatically enqueue emails, and `SendMailJob` to process those emails.
Config options are:
`options`: Options array to be passed to `push` method. It allows to keep emails on a different queue or with different params.
`transport`: Transport class name, to be initialized into `SendMailJob`. Defaults to `MailTransport` as CakePHP does.
Initially I thought it would be a good idea config to be:
```
'default' => [
'options' => QUEUE_OPTIONS
'transport' => [
'className' => TRANSPORT_CLASS_NAME,
'config' => TRANSPORT_CONFIG_ARRAY
]
]
```
But to make it as simple as possible, using the existing `config` and just switching the `className` to `QueueTransport` and adding the actual `transport` is better.
Please let me know your thoughts and if …
> Implement QueueTransport to enqueue emails automatically Fixes #64

- src/Consumption/LimitAttemptsExtension.php
- src/Queue/Processor.php
This allows the exception to be saved to the queue_failed_jobs table without the reason prefix.
Fixes #114
> Set Exception as Property on Message

- docs/en/index.rst
- src/Command/JobCommand.php
- templates/bake/job.twig
- tests/TestCase/Task/JobTaskTest.php
- tests/comparisons/JobTaskWithMaxAttempts.php
- tests/comparisons/JobTaskWithUnique.php
This makes including `maxAttempts` optional when baking jobs similar to `shouldBeUnique`. Specifying the option `--max-attempts [number of attempts]` will include the property in the baked job, otherwise the property won't be included.
> Make max attempts optional in bake job command

- src/Command/WorkerCommand.php
- src/QueueManager.php
- tests/TestCase/Command/WorkerCommandTest.php
- tests/TestCase/Consumption/RemoveUniqueJobIdFromCacheExtensionTest.php
- tests/TestCase/QueueManagerTest.php
Prevents an exception when multiple configs are set with `uniqueCache` configured.
Fixes #113
> Use unique names for queue unique cache configurations

- src/Command/WorkerCommand.php
Fixes #95 ...After adding the parameter processor the issue with enqueue is fixed but we should allow having a default so people don't actually need to pass processor param.
Please let me know your thoughts
> Add default processor if argument is not passed to avoid processor hash
